# Generated by Django 4.2.26 on 2025-11-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='isu',
            field=models.CharField(default=409030, max_length=6, unique=True, verbose_name='Номер ИСУ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('admin', 'Менеджер')], default='student', max_length=20),
        ),
    ]
